// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb4ATmQb4jhhtcOBnMupshA1Z7Ov6fa-M',
    appId: '1:804283490761:web:b0c6722bf4357cf2c50818',
    messagingSenderId: '804283490761',
    projectId: 'uwuchat-24d3b',
    authDomain: 'uwuchat-24d3b.firebaseapp.com',
    storageBucket: 'uwuchat-24d3b.appspot.com',
    measurementId: 'G-1LDM6KDPHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrWWYtX-1l8yjISmUMSN81S-pOXnsueQ0',
    appId: '1:804283490761:android:638dabf53f2c84dec50818',
    messagingSenderId: '804283490761',
    projectId: 'uwuchat-24d3b',
    storageBucket: 'uwuchat-24d3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB51-pMfXwQ5mJrpH00R_scxjZkKoxd8VY',
    appId: '1:804283490761:ios:6cb4965007cb561bc50818',
    messagingSenderId: '804283490761',
    projectId: 'uwuchat-24d3b',
    storageBucket: 'uwuchat-24d3b.appspot.com',
    iosClientId: '804283490761-d4ghf7g8l53t5imcq2iob2usha7o23jt.apps.googleusercontent.com',
    iosBundleId: 'com.example.uwuchat',
  );
}
